if (!require("tidyverse")) install.packages("tidyverse"); library("tidyverse")
if (!require("readxl")) install.packages("readxl"); library("readxl")
if (!require("plotly")) install.packages("plotly")
if (!require("slider")) install.packages("slider")
if (!require("kableExtra")) install.packages("kableExtra")
if (!require("corrplot")) install.packages("corrplot")
